#!/usr/bin/env sh


################################################################################
### Head: Init
##

THE_BASE_DIR_PATH="$(cd -- "$(dirname -- "$0")" ; pwd)"
##THE_OPENBOX_CONFIG_DIR_PATH="$HOME/.config/openbox"
THE_OPENBOX_CONFIG_DIR_PATH="$THE_BASE_DIR_PATH"
THE_OPENBOX_USER_REAL_AUTOSTART_FILE_PATH="$THE_OPENBOX_CONFIG_DIR_PATH/up.sh"

##
### Tail: Init
################################################################################


################################################################################
### Head: Main
##

__main__ () {
	##echo "$THE_OPENBOX_USER_REAL_AUTOSTART_FILE_PATH"

	##"$THE_OPENBOX_USER_REAL_AUTOSTART_FILE_PATH"
	##bash "$THE_OPENBOX_USER_REAL_AUTOSTART_FILE_PATH"


	if test -f $THE_OPENBOX_USER_REAL_AUTOSTART_FILE_PATH; then
		if test -x $THE_OPENBOX_USER_REAL_AUTOSTART_FILE_PATH; then
			exec "$THE_OPENBOX_USER_REAL_AUTOSTART_FILE_PATH"
		fi
	fi


}

__main__

##
### Tail: Main
################################################################################


################################################################################
### Head: Note
##

## * https://github.com/samwhelp/skel-project-plan/blob/gh-pages/demo/sh/project/bin/install.sh


##
## ## Why up.sh
##
## For File: `/usr/lib/openbox/openbox-xdg-autostart`, Run: `sh $AUTOSTART`
## autostart not work, if /usr/bin/sh --> dash
##
## run
##
## ``` sh
## $ grep 'user openbox autostart script' /usr/lib/openbox/openbox-autostart -A 6
## ```
##
## show
##
## ```
## Run the user openbox autostart script
## if test -f $AUTOSTART; then
##     sh $AUTOSTART
## elif test -f $AUTOSTART.sh; then
##     sh $AUTOSTART.sh
## fi
## ```
##



##
## ## openbox xsession start process
##
## ### xsession
##
## * /usr/share/xsessions/openbox.desktop
## * /usr/bin/openbox-session
## * /usr/bin/openbox
##
## ### user autostart
##
## * /usr/lib/openbox/openbox-autostart
## * ~/.config/autostart
## or
## * ~/.config/autostart.sh
##


##
## run
##
## ``` sh
## grep exec /usr/bin/openbox-session
## ```
##
## show
##
## ```
## exec /usr/bin/openbox --startup "/usr/lib/openbox/openbox-autostart OPENBOX" "$@"
## ```
##

##
### Tail: Note
################################################################################
