
default: help
.PHONY: default

help:
	@echo 'Usage:'
	@echo '	$$ make [action]'
	@echo
	@echo 'Ex:'
	@echo '	$$ make'
	@echo '	$$ make help'
	@echo
	@echo '	$$ make install'
	@echo
	@echo '	$$ make package-install'
	@echo
	@echo '	$$ make config-install'
	@echo


.PHONY: help


install:
	@./install.sh
.PHONY: install


config-install:
	@./config-install.sh
.PHONY: config-install


package-install:
	@./package-install.sh
.PHONY: package-install
