
default: help
.PHONY: default

help:
	@echo 'Usage:'
	@echo '	$$ make [action]'
	@echo
	@echo 'Ex:'
	@echo '	$$ make'
	@echo '	$$ make help'
	@echo
	@echo '	$$ make remove'
	@echo
	@echo '	$$ make config-remove'
	@echo


.PHONY: help


remove:
	@./remove.sh
.PHONY: remove


config-remove:
	@./config-remove.sh
.PHONY: config-remove
