#!/usr/bin/env bash

gsettings reset org.xfce.mousepad.preferences.file add-last-end-of-line
gsettings reset org.xfce.mousepad.preferences.file autosave-timer
gsettings reset org.xfce.mousepad.preferences.file default-encoding
gsettings reset org.xfce.mousepad.preferences.file make-backup
gsettings reset org.xfce.mousepad.preferences.file monitor-changes
gsettings reset org.xfce.mousepad.preferences.file monitor-disabling-timer
gsettings reset org.xfce.mousepad.preferences.file session-restore
gsettings reset org.xfce.mousepad.preferences.view auto-indent
gsettings reset org.xfce.mousepad.preferences.view color-scheme
gsettings reset org.xfce.mousepad.preferences.view font-name
gsettings reset org.xfce.mousepad.preferences.view highlight-current-line
gsettings reset org.xfce.mousepad.preferences.view indent-on-tab
gsettings reset org.xfce.mousepad.preferences.view indent-width
gsettings reset org.xfce.mousepad.preferences.view insert-spaces
gsettings reset org.xfce.mousepad.preferences.view match-braces
gsettings reset org.xfce.mousepad.preferences.view right-margin-position
gsettings reset org.xfce.mousepad.preferences.view show-line-endings
gsettings reset org.xfce.mousepad.preferences.view show-line-marks
gsettings reset org.xfce.mousepad.preferences.view show-line-numbers
gsettings reset org.xfce.mousepad.preferences.view show-right-margin
gsettings reset org.xfce.mousepad.preferences.view show-whitespace
gsettings reset org.xfce.mousepad.preferences.view.show-whitespace inside
gsettings reset org.xfce.mousepad.preferences.view.show-whitespace leading
gsettings reset org.xfce.mousepad.preferences.view.show-whitespace trailing
gsettings reset org.xfce.mousepad.preferences.view smart-backspace
gsettings reset org.xfce.mousepad.preferences.view smart-home-end
gsettings reset org.xfce.mousepad.preferences.view tab-width
gsettings reset org.xfce.mousepad.preferences.view use-default-monospace-font
gsettings reset org.xfce.mousepad.preferences.view word-wrap
gsettings reset org.xfce.mousepad.preferences.window always-show-tabs
gsettings reset org.xfce.mousepad.preferences.window client-side-decorations
gsettings reset org.xfce.mousepad.preferences.window cycle-tabs
gsettings reset org.xfce.mousepad.preferences.window default-tab-sizes
gsettings reset org.xfce.mousepad.preferences.window expand-tabs
gsettings reset org.xfce.mousepad.preferences.window menubar-visible-in-fullscreen
gsettings reset org.xfce.mousepad.preferences.window menubar-visible
gsettings reset org.xfce.mousepad.preferences.window old-style-menu
gsettings reset org.xfce.mousepad.preferences.window opening-mode
gsettings reset org.xfce.mousepad.preferences.window path-in-title
gsettings reset org.xfce.mousepad.preferences.window recent-menu-items
gsettings reset org.xfce.mousepad.preferences.window remember-position
gsettings reset org.xfce.mousepad.preferences.window remember-size
gsettings reset org.xfce.mousepad.preferences.window remember-state
gsettings reset org.xfce.mousepad.preferences.window statusbar-visible
gsettings reset org.xfce.mousepad.preferences.window statusbar-visible-in-fullscreen
gsettings reset org.xfce.mousepad.preferences.window toolbar-icon-size
gsettings reset org.xfce.mousepad.preferences.window toolbar-style
gsettings reset org.xfce.mousepad.preferences.window toolbar-visible
gsettings reset org.xfce.mousepad.preferences.window toolbar-visible-in-fullscreen
